import numpy as np
import pandas as pd 

df = pd.read_csv('data/application_train.csv')

column_translation = {
    'SK_ID_CURR': 'Identifiant du client',
    'TARGET': 'Cible (0 = non défaut, 1 = défaut)',
    'NAME_CONTRACT_TYPE': 'Type de contrat',
    'CODE_GENDER': 'Code du genre',
    'FLAG_OWN_CAR': 'Indicateur de propriété d\'une voiture',
    'FLAG_OWN_REALTY': 'Indicateur de propriété immobilière',
    'CNT_CHILDREN': 'Nombre d\'enfants',
    'AMT_INCOME_TOTAL': 'Revenu total',
    'AMT_CREDIT': 'Montant du crédit',
    'AMT_ANNUITY': 'Montant de l\'annuité',
    'AMT_GOODS_PRICE': 'Prix des biens',
    'NAME_TYPE_SUITE': 'Type de suite',
    'NAME_INCOME_TYPE': 'Type de revenu',
    'NAME_EDUCATION_TYPE': 'Type d\'éducation',
    'NAME_FAMILY_STATUS': 'Statut familial',
    'NAME_HOUSING_TYPE': 'Type de logement',
    'REGION_POPULATION_RELATIVE': 'Population relative de la région',
    'DAYS_BIRTH': 'Jours depuis la naissance',
    'DAYS_EMPLOYED': 'Jours d\'emploi',
    'DAYS_REGISTRATION': 'Jours d\'enregistrement',
    'DAYS_ID_PUBLISH': 'Jours depuis la publication de l\'identité',
    'OWN_CAR_AGE': 'Âge de la voiture',
    'FLAG_MOBIL': 'Indicateur de mobile',
    'FLAG_EMP_PHONE': 'Indicateur de téléphone professionnel',
    'FLAG_WORK_PHONE': 'Indicateur de téléphone de travail',
    'FLAG_CONT_MOBILE': 'Indicateur de mobile de contact',
    'FLAG_PHONE': 'Indicateur de téléphone',
    'FLAG_EMAIL': 'Indicateur d\'email',
    'OCCUPATION_TYPE': 'Type d\'occupation',
    'CNT_FAM_MEMBERS': 'Nombre de membres de la famille',
    'REGION_RATING_CLIENT': 'Notation de la région du client',
    'REGION_RATING_CLIENT_W_CITY': 'Notation de la région du client avec la ville',
    'WEEKDAY_APPR_PROCESS_START': 'Jour de la semaine de début du processus',
    'HOUR_APPR_PROCESS_START': 'Heure de début du processus',
    'REG_REGION_NOT_LIVE_REGION': 'Région enregistrée différente de la région d\'habitation',
    'REG_REGION_NOT_WORK_REGION': 'Région enregistrée différente de la région de travail',
    'LIVE_REGION_NOT_WORK_REGION': 'Région d\'habitation différente de la région de travail',
    'REG_CITY_NOT_LIVE_CITY': 'Ville enregistrée différente de la ville d\'habitation',
    'REG_CITY_NOT_WORK_CITY': 'Ville enregistrée différente de la ville de travail',
    'LIVE_CITY_NOT_WORK_CITY': 'Ville d\'habitation différente de la ville de travail',
    'ORGANIZATION_TYPE': 'Type d\'organisation',
    'EXT_SOURCE_1': 'Source externe 1',
    'EXT_SOURCE_2': 'Source externe 2',
    'EXT_SOURCE_3': 'Source externe 3',
    'APARTMENTS_AVG': 'Moyenne des appartements',
    'BASEMENTAREA_AVG': 'Moyenne de la surface du sous-sol',
    'YEARS_BEGINEXPLUATATION_AVG': 'Moyenne des années de début d\'exploitation',
    'YEARS_BUILD_AVG': 'Moyenne des années de construction',
    'COMMONAREA_AVG': 'Moyenne de la surface commune',
    'ELEVATORS_AVG': 'Moyenne des ascenseurs',
    'ENTRANCES_AVG': 'Moyenne des entrées',
    'FLOORSMAX_AVG': 'Moyenne des étages maximum',
    'FLOORSMIN_AVG': 'Moyenne des étages minimum',
    'LANDAREA_AVG': 'Moyenne de la surface du terrain',
    'LIVINGAPARTMENTS_AVG': 'Moyenne des appartements habitables',
    'LIVINGAREA_AVG': 'Moyenne de la surface habitable',
    'NONLIVINGAPARTMENTS_AVG': 'Moyenne des appartements non habitables',
    'NONLIVINGAREA_AVG': 'Moyenne de la surface non habitable',
    'APARTMENTS_MODE': 'Mode des appartements',
    'BASEMENTAREA_MODE': 'Mode de la surface du sous-sol',
    'YEARS_BEGINEXPLUATATION_MODE': 'Mode des années de début d\'exploitation',
    'YEARS_BUILD_MODE': 'Mode des années de construction',
    'COMMONAREA_MODE': 'Mode de la surface commune',
    'ELEVATORS_MODE': 'Mode des ascenseurs',
    'ENTRANCES_MODE': 'Mode des entrées',
    'FLOORSMAX_MODE': 'Mode des étages maximum',
    'FLOORSMIN_MODE': 'Mode des étages minimum',
    'LANDAREA_MODE': 'Mode de la surface du terrain',
    'LIVINGAPARTMENTS_MODE': 'Mode des appartements habitables',
    'LIVINGAREA_MODE': 'Mode de la surface habitable',
    'NONLIVINGAPARTMENTS_MODE': 'Mode des appartements non habitables',
    'NONLIVINGAREA_MODE': 'Mode de la surface non habitable',
    'APARTMENTS_MEDI': 'Médiane des appartements',
    'BASEMENTAREA_MEDI': 'Médiane de la surface du sous-sol',
    'YEARS_BEGINEXPLUATATION_MEDI': 'Médiane des années de début d\'exploitation',
    'YEARS_BUILD_MEDI': 'Médiane des années de construction',
    'COMMONAREA_MEDI': 'Médiane de la surface commune',
    'ELEVATORS_MEDI': 'Médiane des ascenseurs',
    'ENTRANCES_MEDI': 'Médiane des entrées',
    'FLOORSMAX_MEDI': 'Médiane des étages maximum',
    'FLOORSMIN_MEDI': 'Médiane des étages minimum',
    'LANDAREA_MEDI': 'Médiane de la surface du terrain',
    'LIVINGAPARTMENTS_MEDI': 'Médiane des appartements habitables',
    'LIVINGAREA_MEDI': 'Médiane de la surface habitable',
    'NONLIVINGAPARTMENTS_MEDI': 'Médiane des appartements non habitables',
    'NONLIVINGAREA_MEDI': 'Médiane de la surface non habitable',
    'FONDKAPREMONT_MODE': 'Mode de Fondkapremont',
    'HOUSETYPE_MODE': 'Mode du type de maison',
    'TOTALAREA_MODE': 'Mode de la surface totale',
    'WALLSMATERIAL_MODE': 'Mode du matériau des murs',
    'EMERGENCYSTATE_MODE': 'Mode de l\'état d\'urgence',
    'OBS_30_CNT_SOCIAL_CIRCLE': 'Observations à 30 jours du cercle social',
    'DEF_30_CNT_SOCIAL_CIRCLE': 'Défauts à 30 jours du cercle social',
    'OBS_60_CNT_SOCIAL_CIRCLE': 'Observations à 60 jours du cercle social',
    'DEF_60_CNT_SOCIAL_CIRCLE': 'Défauts à 60 jours du cercle social',
    'DAYS_LAST_PHONE_CHANGE': 'Jours depuis le dernier changement de téléphone',
    'FLAG_DOCUMENT_2': 'Indicateur du document 2',
    'FLAG_DOCUMENT_3': 'Indicateur du document 3',
    'FLAG_DOCUMENT_4': 'Indicateur du document 4',
    'FLAG_DOCUMENT_5': 'Indicateur du document 5',
    'FLAG_DOCUMENT_6': 'Indicateur du document 6',
    'FLAG_DOCUMENT_7': 'Indicateur du document 7',
    'FLAG_DOCUMENT_8': 'Indicateur du document 8',
    'FLAG_DOCUMENT_9': 'Indicateur du document 9',
    'FLAG_DOCUMENT_10': 'Indicateur du document 10',
    'FLAG_DOCUMENT_11': 'Indicateur du document 11',
    'FLAG_DOCUMENT_12': 'Indicateur du document 12',
    'FLAG_DOCUMENT_13': 'Indicateur du document 13',
    'FLAG_DOCUMENT_14': 'Indicateur du document 14',
    'FLAG_DOCUMENT_15': 'Indicateur du document 15',
    'FLAG_DOCUMENT_16': 'Indicateur du document 16',
    'FLAG_DOCUMENT_17': 'Indicateur du document 17',
    'FLAG_DOCUMENT_18': 'Indicateur du document 18',
    'FLAG_DOCUMENT_19': 'Indicateur du document 19',
    'FLAG_DOCUMENT_20': 'Indicateur du document 20',
    'FLAG_DOCUMENT_21': 'Indicateur du document 21',
    'AMT_REQ_CREDIT_BUREAU_HOUR': 'Montant demandé à l\'agence de crédit (heure)',
    'AMT_REQ_CREDIT_BUREAU_DAY': 'Montant demandé à l\'agence de crédit (jour)',
    'AMT_REQ_CREDIT_BUREAU_WEEK': 'Montant demandé à l\'agence de crédit (semaine)',
    'AMT_REQ_CREDIT_BUREAU_MON': 'Montant demandé à l\'agence de crédit (mois)',
    'AMT_REQ_CREDIT_BUREAU_QRT': 'Montant demandé à l\'agence de crédit (trimestre)',
    'AMT_REQ_CREDIT_BUREAU_YEAR': 'Montant demandé à l\'agence de crédit (année)'
}

df.to_csv('data/application_train.csv',index=False)